import { ColumnTitleProps, FullProfile } from './types';

export const PROFILE_DESCRIPTION_DICT: {
    [key in keyof FullProfile]: ColumnTitleProps;
} = {
    waterTemperature: { name: 'Water Temperature', unit: 'degC' },
    adsorbentDensity: { name: 'Adsorbent Density', unit: 'g/cm^3' },
    adsorbentParticlePorosity: { name: 'Adsorbent Particle Porosity', unit: '' },
    adsorbentParticleRadius: { name: 'Adsorbent Particle Radius', unit: 'cm' },
    bedDiameter: { name: 'Bed Diameter', unit: 'cm' },
    bedLength: { name: 'Bed Length', unit: 'cm' },
    bedFlowrate: { name: 'Bed Flowrate', unit: 'mL/mins' },
    bedMass: { name: 'Bed Mass', unit: 'g' },
    tortuosity: { name: 'Tortuosity', unit: '' },
    spdfr: { name: 'SPDFR', unit: '' },
    frendlichK: { name: 'Frendlich K', unit: '' },
    frendlichNth: { name: 'Frendlich 1/n', unit: '' },
    initConcent: { name: 'Initial Concentration', unit: 'ug/L' },
    contaminantMolarVolume: { name: 'Contaminant Molar Volume', unit: 'mL/mol' },
    surfaceDiffusion: { name: 'Surface Diffusion', unit: 'cm^2/mins' },
    poreDiffusion: { name: 'Pore Diffusion', unit: 'cm^2/mins' },
    filmDiffusion: { name: 'Film Diffusion', unit: 'cm/mins' },
    // Calculation Results
    bedCrossSectionalArea: { name: 'Bed Cross Sectional Area', unit: 'cm^2' },
    bedVolume: { name: 'Bed Volume', unit: 'L' },
    bedDensity: { name: 'Bed Density', unit: 'g/m^3' },
    bedPorosity: { name: 'Bed Porosity', unit: '' },
    ebct: { name: 'EBCT', unit: 'mins' },
    hlr: { name: 'HLR', unit: 'cm/mins' },
    interstitialVelocity: { name: 'Interstitial Velocity', unit: 'cm/mins' },
    waterDensity: { name: 'Water Density', unit: 'g/cm^3' },
    waterKineticViscosity: { name: 'Water Kinetic Viscosity', unit: 'cm^2/mins' },
    waterDynamicViscosity: { name: 'Water Dynamic Viscosity', unit: 'g/(cm mins)' },
    diffusivityInWater: { name: 'Water Diffusivity', unit: 'cm^2/mins' },
    nReynolds: { name: 'Reynolds Number', unit: '' },
    nSchmidt: { name: 'Schmidt Number', unit: '' },
    multipliedScRe: { name: 'Sc * Re', unit: '' },
    dispersionCoeffi: { name: 'Dispersion Coefficient', unit: 'cm^2/mins' },
    nPeclet: { name: 'Peclet Number', unit: '' },
    nStanton: { name: 'Stanton Number', unit: '' },
    mStanton: { name: 'Modified Stanton Number', unit: '' },
    adsorptionCap: { name: 'Adsorption Capacity', unit: 'ug/g' },
    surfaceSoluteDistParam: { name: 'Surface Solute Distribution Parameter', unit: '' },
    poreSoluteDistParam: { name: 'Pore Solute Distribution Parameter', unit: '' },
    surfaceDiffusionMod: { name: 'Surface Diffusion Modulus', unit: '' },
    poreDiffusionMod: { name: 'Pore Diffusion Modulus', unit: '' },
    nPoreBiot: { name: 'Pore Biot Number', unit: '' },
    mPoreBiot: { name: 'Modified Pore Biot Number', unit: '' },
    nSurfaceBiot: { name: 'Surface Biot Number', unit: '' },
    mSurfaceBiot: { name: 'Surface Biot Number', unit: '' }
};
